using Freista;
using System.ComponentModel;

namespace AppointmentTests;

/// <summary>
/// Scenarios authored as plain C#. The generator lowers each body into a graph the runtime runs,
/// reporting every Given/When/Then step as its own xUnit test. xUnit never executes these bodies
/// directly — they are source for the generator.
/// </summary>
[DisplayName("Appointment booking")]
public static class Scenarios
{
    // Linear: statements run in source order. CreateAppointment depends on both arrange steps.
    [Scenario("customer books an appointment")]
    public static async Task Booking()
    {
        var patient = await Given.PatientExists("Jane");
        var slot = await Given.AvailableSlot();

        var appointment = await When.CreateAppointment(patient, slot);

        await Then.AppointmentExists(appointment);
    }

    // Explicit fork/join with an awaited tuple: the two arrange steps run in parallel after the
    // clean step, and CreateAppointment waits for both.
    [Scenario("customer books with parallel arrange")]
    public static async Task BookingWithParallelArrange()
    {
        await Given.DatabaseIsClean();

        var (patient, slot) = await (
            Given.PatientExists("Jane"),
            Given.AvailableSlot());

        var appointment = await When.CreateAppointment(patient, slot);

        await Then.AppointmentExists(appointment);
    }

    // Homogeneous bulk parallelism with an awaited explicit array.
    [Scenario("bulk user import")]
    public static async Task ImportUsers()
    {
        var users = await new[]
        {
            Given.UserExists("alice"),
            Given.UserExists("bob"),
        };

        var import = await When.ImportUsers(users);

        await Then.ImportShouldContainUsers(import, 2);
    }

    // The same bulk form generated by LINQ; the constant range is unrolled into one step per user.
    [Scenario("bulk user import via LINQ")]
    public static async Task ImportUsersViaLinq()
    {
        var users = await Enumerable.Range(1, 3)
            .Select(i => Given.UserExists($"user-{i}"))
            .ToArray();

        var import = await When.ImportUsers(users);

        await Then.ImportShouldContainUsers(import, 3);
    }
}
