using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis.CSharp;
using PUnit.Generator.Lowering;

namespace PUnit.Generator.Emit;

/// <summary>Emits the generated C# source for a set of lowered scenarios.</summary>
internal static class ScenarioEmitter
{
    static readonly string[] RequiredUsings =
    [
        "using PUnit;",
        "using System.Linq;",
        "using System.Threading.Tasks;",
    ];

    public static string Emit(IReadOnlyList<ParsedScenario> scenarios)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS1591");

        foreach (var u in CollectUsings(scenarios))
        {
            sb.AppendLine(u);
        }

        sb.AppendLine();
        sb.AppendLine("namespace PUnit.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    internal static class PUnitGenerated");
        sb.AppendLine("    {");

        EmitCreateAll(sb, scenarios);
        EmitModuleInitializer(sb, scenarios);

        foreach (var scenario in scenarios)
        {
            EmitScenarioBuilder(sb, scenario);
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    static IEnumerable<string> CollectUsings(IReadOnlyList<ParsedScenario> scenarios)
    {
        var seen = new HashSet<string>();
        foreach (var u in RequiredUsings)
        {
            if (seen.Add(u))
            {
                yield return u;
            }
        }

        foreach (var scenario in scenarios)
        {
            foreach (var u in scenario.Usings)
            {
                if (seen.Add(u))
                {
                    yield return u;
                }
            }
        }
    }

    static void EmitCreateAll(StringBuilder sb, IReadOnlyList<ParsedScenario> scenarios)
    {
        sb.AppendLine("        public static global::System.Collections.Generic.IReadOnlyList<global::PUnit.Model.ScenarioDefinition> CreateAll()");
        if (scenarios.Count == 0)
        {
            sb.AppendLine("            => global::System.Array.Empty<global::PUnit.Model.ScenarioDefinition>();");
            sb.AppendLine();
            return;
        }

        sb.AppendLine("            => new global::PUnit.Model.ScenarioDefinition[]");
        sb.AppendLine("            {");
        foreach (var scenario in scenarios)
        {
            sb.AppendLine($"                Scenario_{scenario.SafeName}(),");
        }

        sb.AppendLine("            };");
        sb.AppendLine();
    }

    static void EmitModuleInitializer(StringBuilder sb, IReadOnlyList<ParsedScenario> scenarios)
    {
        sb.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("        internal static void Initialize()");
        sb.AppendLine("        {");
        foreach (var scenario in scenarios)
        {
            sb.AppendLine(
                $"            global::PUnit.ScenarioRegistry.Register({Literal(scenario.MethodFullName)}, Scenario_{scenario.SafeName});");
        }

        sb.AppendLine("        }");
        sb.AppendLine();
    }

    static void EmitScenarioBuilder(StringBuilder sb, ParsedScenario scenario)
    {
        sb.AppendLine($"        public static global::PUnit.Model.ScenarioDefinition Scenario_{scenario.SafeName}()");
        sb.AppendLine("        {");
        sb.AppendLine($"            var nodes = new global::PUnit.Model.ScenarioNode[{scenario.Steps.Count}];");

        foreach (var step in scenario.Steps)
        {
            EmitNode(sb, step);
        }

        sb.AppendLine("            return new global::PUnit.Model.ScenarioDefinition");
        sb.AppendLine("            {");
        sb.AppendLine($"                ScenarioId = {Literal(scenario.ScenarioId)},");
        sb.AppendLine($"                DisplayName = {Literal(scenario.DisplayName)},");
        sb.AppendLine($"                MethodName = {Literal(scenario.MethodFullName)},");
        sb.AppendLine($"                SourceFile = {Literal(scenario.SourceFile)},");
        sb.AppendLine($"                SourceLine = {scenario.SourceLine},");
        sb.AppendLine($"                Timeout = {Timeout(scenario.TimeoutMs)},");
        sb.AppendLine("                Nodes = nodes,");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    static void EmitNode(StringBuilder sb, ParsedStep step)
    {
        sb.AppendLine($"            nodes[{step.Index}] = new global::PUnit.Model.ScenarioNode");
        sb.AppendLine("            {");
        sb.AppendLine($"                Index = {step.Index},");
        sb.AppendLine($"                StepId = {Literal(step.StepId)},");
        sb.AppendLine($"                Phase = {Literal(step.Phase)},");
        sb.AppendLine($"                OperationName = {Literal(step.OperationName)},");
        sb.AppendLine($"                DisplayNameTemplate = {Literal(step.DisplayNameTemplate)},");
        sb.AppendLine($"                SourceFile = {Literal(step.SourceFile)},");
        sb.AppendLine($"                SourceLine = {step.SourceLine},");
        sb.AppendLine($"                GroupId = {Literal(step.GroupId)},");
        sb.AppendLine($"                Timeout = {Timeout(step.TimeoutMs)},");
        sb.AppendLine($"                DependsOn = new int[] {{ {string.Join(", ", step.DependsOn)} }},");
        sb.AppendLine("                Invoke = static async (__inputs, __ctx) =>");
        sb.AppendLine("                {");
        if (step.HasResult)
        {
            sb.AppendLine($"                    var __r = await {step.InvokeCallText};");
            sb.AppendLine("                    return (object?)__r;");
        }
        else
        {
            sb.AppendLine($"                    await {step.InvokeCallText};");
            sb.AppendLine("                    return (object?)null;");
        }

        sb.AppendLine("                },");

        if (step.FormatExpression is not null)
        {
            sb.AppendLine($"                FormatDisplayName = static __inputs => {step.FormatExpression},");
        }

        sb.AppendLine("            };");
    }

    static string Timeout(int ms)
        => ms > 0 ? $"global::System.TimeSpan.FromMilliseconds({ms})" : "null";

    static string Literal(string? value)
        => value is null ? "null" : SyntaxFactory.Literal(value).ToString();
}
