using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using PUnit.Generator.Lowering;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace PUnit.Generator.Emit;

/// <summary>Emits the generated C# source for a set of lowered scenarios as a Roslyn syntax tree.</summary>
internal static class ScenarioEmitter
{
    const string Header = "// <auto-generated/>\n#nullable enable\n#pragma warning disable CS1591\n";

    static readonly string[] RequiredUsings =
    [
        "using PUnit;",
        "using System.Linq;",
        "using System.Threading.Tasks;",
    ];

    public static string Emit(IReadOnlyList<ParsedScenario> scenarios)
    {
        var members = new List<MemberDeclarationSyntax>
        {
            BuildCreateAll(scenarios),
            BuildModuleInitializer(scenarios),
        };
        members.AddRange(scenarios.Select(BuildScenarioBuilder));

        var classDecl = ClassDeclaration("PUnitGenerated")
            .AddModifiers(Token(SyntaxKind.InternalKeyword), Token(SyntaxKind.StaticKeyword))
            .WithMembers(List(members));

        var nsDecl = NamespaceDeclaration(ParseName("PUnit.Generated")).AddMembers(classDecl);

        // CollectUsings yields full "using X;" lines (incl. static/aliased forms); parse them as a
        // unit so every using-directive shape is handled correctly.
        var usings = ParseCompilationUnit(string.Join("\n", CollectUsings(scenarios))).Usings;

        var unit = CompilationUnit()
            .WithUsings(usings)
            .AddMembers(nsDecl)
            .NormalizeWhitespace(eol: "\n");

        return Header + unit.ToFullString() + "\n";
    }

    static IEnumerable<string> CollectUsings(IReadOnlyList<ParsedScenario> scenarios)
    {
        var seen = new HashSet<string>();
        foreach (var u in RequiredUsings)
        {
            if (seen.Add(u))
            {
                yield return u;
            }
        }

        foreach (var scenario in scenarios)
        {
            foreach (var u in scenario.Usings)
            {
                if (seen.Add(u))
                {
                    yield return u;
                }
            }
        }
    }

    static MethodDeclarationSyntax BuildCreateAll(IReadOnlyList<ParsedScenario> scenarios)
    {
        var body = scenarios.Count == 0
            ? "global::System.Array.Empty<global::PUnit.Model.ScenarioDefinition>()"
            : "new global::PUnit.Model.ScenarioDefinition[] { "
              + string.Join(", ", scenarios.Select(s => $"Scenario_{s.SafeName}()"))
              + " }";

        return MethodDeclaration(
                ParseTypeName("global::System.Collections.Generic.IReadOnlyList<global::PUnit.Model.ScenarioDefinition>"),
                "CreateAll")
            .AddModifiers(Token(SyntaxKind.PublicKeyword), Token(SyntaxKind.StaticKeyword))
            .WithExpressionBody(ArrowExpressionClause(ParseExpression(body)))
            .WithSemicolonToken(Token(SyntaxKind.SemicolonToken));
    }

    static MethodDeclarationSyntax BuildModuleInitializer(IReadOnlyList<ParsedScenario> scenarios)
    {
        var statements = scenarios.Select(s => ParseStatement(
            $"global::PUnit.ScenarioRegistry.Register({LiteralText(s.MethodFullName)}, Scenario_{s.SafeName});"));

        return MethodDeclaration(PredefinedType(Token(SyntaxKind.VoidKeyword)), "Initialize")
            .AddAttributeLists(AttributeList(SingletonSeparatedList(
                Attribute(ParseName("global::System.Runtime.CompilerServices.ModuleInitializer")))))
            .AddModifiers(Token(SyntaxKind.InternalKeyword), Token(SyntaxKind.StaticKeyword))
            .WithBody(Block(statements));
    }

    static MemberDeclarationSyntax BuildScenarioBuilder(ParsedScenario scenario)
    {
        var statements = new List<StatementSyntax>
        {
            ParseStatement($"var nodes = new global::PUnit.Model.ScenarioNode[{scenario.Steps.Count}];"),
        };

        foreach (var step in scenario.Steps)
        {
            var assignment = AssignmentExpression(
                SyntaxKind.SimpleAssignmentExpression,
                ElementAccessExpression(IdentifierName("nodes"))
                    .WithArgumentList(BracketedArgumentList(SingletonSeparatedList(Argument(Num(step.Index))))),
                BuildNode(step));
            statements.Add(ExpressionStatement(assignment));
        }

        var definition = ObjectCreationExpression(ParseTypeName("global::PUnit.Model.ScenarioDefinition"))
            .WithInitializer(InitializerExpression(SyntaxKind.ObjectInitializerExpression, SeparatedList<ExpressionSyntax>(
            [
                Set("ScenarioId", Lit(scenario.ScenarioId)),
                Set("DisplayName", Lit(scenario.DisplayName)),
                Set("MethodName", Lit(scenario.MethodFullName)),
                Set("SourceFile", Lit(scenario.SourceFile)),
                Set("SourceLine", Num(scenario.SourceLine)),
                Set("Timeout", Timeout(scenario.TimeoutMs)),
                Set("Nodes", IdentifierName("nodes")),
            ])));

        statements.Add(ReturnStatement(definition));

        return MethodDeclaration(
                ParseTypeName("global::PUnit.Model.ScenarioDefinition"),
                $"Scenario_{scenario.SafeName}")
            .AddModifiers(Token(SyntaxKind.PublicKeyword), Token(SyntaxKind.StaticKeyword))
            .WithBody(Block(statements));
    }

    static ObjectCreationExpressionSyntax BuildNode(ParsedStep step)
    {
        var members = new List<ExpressionSyntax>
        {
            Set("Index", Num(step.Index)),
            Set("StepId", Lit(step.StepId)),
            Set("Phase", Lit(step.Phase)),
            Set("OperationName", Lit(step.OperationName)),
            Set("DisplayNameTemplate", Lit(step.DisplayNameTemplate)),
            Set("SourceFile", Lit(step.SourceFile)),
            Set("SourceLine", Num(step.SourceLine)),
            Set("GroupId", Lit(step.GroupId)),
            Set("Timeout", Timeout(step.TimeoutMs)),
            Set("DependsOn", ParseExpression($"new int[] {{ {string.Join(", ", step.DependsOn)} }}")),
            Set("Invoke", ParseExpression(InvokeLambda(step))),
        };

        if (step.FormatExpression is not null)
        {
            members.Add(Set("FormatDisplayName", ParseExpression($"static __inputs => {step.FormatExpression}")));
        }

        return ObjectCreationExpression(ParseTypeName("global::PUnit.Model.ScenarioNode"))
            .WithInitializer(InitializerExpression(SyntaxKind.ObjectInitializerExpression, SeparatedList(members)));
    }

    static string InvokeLambda(ParsedStep step)
        => step.HasResult
            ? $"static async (__inputs, __ctx) => {{ var __r = await {step.InvokeCallText}; return (object?)__r; }}"
            : $"static async (__inputs, __ctx) => {{ await {step.InvokeCallText}; return (object?)null; }}";

    static AssignmentExpressionSyntax Set(string member, ExpressionSyntax value)
        => AssignmentExpression(SyntaxKind.SimpleAssignmentExpression, IdentifierName(member), value);

    static LiteralExpressionSyntax Num(int value)
        => LiteralExpression(SyntaxKind.NumericLiteralExpression, Literal(value));

    static LiteralExpressionSyntax Lit(string? value)
        => value is null
            ? LiteralExpression(SyntaxKind.NullLiteralExpression)
            : LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(value));

    static ExpressionSyntax Timeout(int ms)
        => ms > 0
            ? ParseExpression($"global::System.TimeSpan.FromMilliseconds({ms.ToString(CultureInfo.InvariantCulture)})")
            : LiteralExpression(SyntaxKind.NullLiteralExpression);

    static string LiteralText(string value) => Literal(value).ToString();
}
