using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using PUnit.Generator.Lowering;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace PUnit.Generator.Emit;

/// <summary>Emits the generated C# source for a set of lowered scenarios as a Roslyn syntax tree.</summary>
internal static class ScenarioEmitter
{
    const string Header = "// <auto-generated/>\n#nullable enable\n#pragma warning disable CS1591\n";

    static readonly string[] RequiredUsings =
    [
        "using PUnit;",
        "using System.Linq;",
        "using System.Threading.Tasks;",
    ];

    public static string Emit(IReadOnlyList<ParsedScenario> scenarios)
    {
        var members = new List<MemberDeclarationSyntax>
        {
            BuildCreateAll(scenarios),
            BuildModuleInitializer(scenarios),
        };
        members.AddRange(scenarios.Select(BuildScenarioBuilder));

        var classDecl = ClassDeclaration("PUnitGenerated")
            .AddModifiers(Token(SyntaxKind.InternalKeyword), Token(SyntaxKind.StaticKeyword))
            .WithMembers(List(members));

        var nsDecl = NamespaceDeclaration(ParseName("PUnit.Generated")).AddMembers(classDecl);

        // CollectUsings yields full "using X;" lines (incl. static/aliased forms); parse them as a
        // unit so every using-directive shape is handled correctly.
        var usings = ParseCompilationUnit(string.Join("\n", CollectUsings(scenarios))).Usings;

        var unit = CompilationUnit()
            .WithUsings(usings)
            .AddMembers(nsDecl)
            .NormalizeWhitespace(eol: "\n");

        return Header + unit.ToFullString() + "\n";
    }

    static IEnumerable<string> CollectUsings(IReadOnlyList<ParsedScenario> scenarios)
    {
        var seen = new HashSet<string>();
        foreach (var u in RequiredUsings)
        {
            if (seen.Add(u))
            {
                yield return u;
            }
        }

        foreach (var scenario in scenarios)
        {
            foreach (var u in scenario.Usings)
            {
                if (seen.Add(u))
                {
                    yield return u;
                }
            }
        }
    }

    static MethodDeclarationSyntax BuildCreateAll(IReadOnlyList<ParsedScenario> scenarios)
    {
        ExpressionSyntax body;
        if (scenarios.Count == 0)
        {
            // global::System.Array.Empty<global::PUnit.Model.ScenarioDefinition>()
            body = InvocationExpression(
                MemberAccessExpression(
                    SyntaxKind.SimpleMemberAccessExpression,
                    ParseName("global::System.Array"),
                    GenericName(Identifier("Empty"))
                        .WithTypeArgumentList(TypeArgumentList(SingletonSeparatedList<TypeSyntax>(
                            ParseTypeName("global::PUnit.Model.ScenarioDefinition"))))))
                .WithArgumentList(ArgumentList());
        }
        else
        {
            // new global::PUnit.Model.ScenarioDefinition[] { Scenario_X(), ... }
            var calls = scenarios.Select(s =>
                (ExpressionSyntax)InvocationExpression(IdentifierName($"Scenario_{s.SafeName}"))
                    .WithArgumentList(ArgumentList()));
            body = ArrayCreationExpression(
                ArrayType(ParseTypeName("global::PUnit.Model.ScenarioDefinition"))
                    .WithRankSpecifiers(SingletonList(
                        ArrayRankSpecifier(SingletonSeparatedList<ExpressionSyntax>(
                            OmittedArraySizeExpression())))))
                .WithInitializer(InitializerExpression(
                    SyntaxKind.ArrayInitializerExpression,
                    SeparatedList<ExpressionSyntax>(calls)));
        }

        return MethodDeclaration(
                ParseTypeName("global::System.Collections.Generic.IReadOnlyList<global::PUnit.Model.ScenarioDefinition>"),
                "CreateAll")
            .AddModifiers(Token(SyntaxKind.PublicKeyword), Token(SyntaxKind.StaticKeyword))
            .WithExpressionBody(ArrowExpressionClause(body))
            .WithSemicolonToken(Token(SyntaxKind.SemicolonToken));
    }

    static MethodDeclarationSyntax BuildModuleInitializer(IReadOnlyList<ParsedScenario> scenarios)
    {
        // global::PUnit.ScenarioRegistry.Register("...", Scenario_X);
        var statements = scenarios.Select(s =>
            (StatementSyntax)ExpressionStatement(
                InvocationExpression(
                    MemberAccessExpression(
                        SyntaxKind.SimpleMemberAccessExpression,
                        ParseName("global::PUnit.ScenarioRegistry"),
                        IdentifierName("Register")))
                    .WithArgumentList(ArgumentList(SeparatedList<ArgumentSyntax>(new[]
                    {
                        Argument(Lit(s.MethodFullName)),
                        Argument(IdentifierName($"Scenario_{s.SafeName}")),
                    })))));

        return MethodDeclaration(PredefinedType(Token(SyntaxKind.VoidKeyword)), "Initialize")
            .AddAttributeLists(AttributeList(SingletonSeparatedList(
                Attribute(ParseName("global::System.Runtime.CompilerServices.ModuleInitializer")))))
            .AddModifiers(Token(SyntaxKind.InternalKeyword), Token(SyntaxKind.StaticKeyword))
            .WithBody(Block(statements));
    }

    static MemberDeclarationSyntax BuildScenarioBuilder(ParsedScenario scenario)
    {
        // var nodes = new global::PUnit.Model.ScenarioNode[N];
        var arrayExpr = ArrayCreationExpression(
            ArrayType(ParseTypeName("global::PUnit.Model.ScenarioNode"))
                .WithRankSpecifiers(SingletonList(
                    ArrayRankSpecifier(SingletonSeparatedList<ExpressionSyntax>(
                        Num(scenario.Steps.Count))))));

        var nodesDecl = LocalDeclarationStatement(
            VariableDeclaration(IdentifierName("var"))
                .WithVariables(SingletonSeparatedList(
                    VariableDeclarator(Identifier("nodes"))
                        .WithInitializer(EqualsValueClause(arrayExpr)))));

        var statements = new List<StatementSyntax> { nodesDecl };

        foreach (var step in scenario.Steps)
        {
            var assignment = AssignmentExpression(
                SyntaxKind.SimpleAssignmentExpression,
                ElementAccessExpression(IdentifierName("nodes"))
                    .WithArgumentList(BracketedArgumentList(SingletonSeparatedList(Argument(Num(step.Index))))),
                BuildNode(step));
            statements.Add(ExpressionStatement(assignment));
        }

        var definition = ObjectCreationExpression(ParseTypeName("global::PUnit.Model.ScenarioDefinition"))
            .WithInitializer(InitializerExpression(SyntaxKind.ObjectInitializerExpression, SeparatedList<ExpressionSyntax>(
            [
                Set("ScenarioId", Lit(scenario.ScenarioId)),
                Set("DisplayName", Lit(scenario.DisplayName)),
                Set("MethodName", Lit(scenario.MethodFullName)),
                Set("SourceFile", Lit(scenario.SourceFile)),
                Set("SourceLine", Num(scenario.SourceLine)),
                Set("Timeout", Timeout(scenario.TimeoutMs)),
                Set("Nodes", IdentifierName("nodes")),
            ])));

        statements.Add(ReturnStatement(definition));

        return MethodDeclaration(
                ParseTypeName("global::PUnit.Model.ScenarioDefinition"),
                $"Scenario_{scenario.SafeName}")
            .AddModifiers(Token(SyntaxKind.PublicKeyword), Token(SyntaxKind.StaticKeyword))
            .WithBody(Block(statements));
    }

    static ObjectCreationExpressionSyntax BuildNode(ParsedStep step)
    {
        var members = new List<ExpressionSyntax>
        {
            Set("Index", Num(step.Index)),
            Set("StepId", Lit(step.StepId)),
            Set("Phase", Lit(step.Phase)),
            Set("OperationName", Lit(step.OperationName)),
            Set("DisplayNameTemplate", Lit(step.DisplayNameTemplate)),
            Set("SourceFile", Lit(step.SourceFile)),
            Set("SourceLine", Num(step.SourceLine)),
            Set("GroupId", Lit(step.GroupId)),
            Set("Timeout", Timeout(step.TimeoutMs)),
            Set("DependsOn", IntArray(step.DependsOn)),
            Set("Invoke", BuildInvokeLambda(step)),
        };

        if (step.FormatExpression is not null)
        {
            members.Add(Set("FormatDisplayName",
                SimpleLambdaExpression(Parameter(Identifier("__inputs")))
                    .WithModifiers(TokenList(Token(SyntaxKind.StaticKeyword)))
                    .WithExpressionBody(ParseExpression(step.FormatExpression))));
        }

        return ObjectCreationExpression(ParseTypeName("global::PUnit.Model.ScenarioNode"))
            .WithInitializer(InitializerExpression(SyntaxKind.ObjectInitializerExpression, SeparatedList(members)));
    }

    /// <summary>
    /// Builds: <c>static async (__inputs, __ctx) => { var __r = await CALL; return (object?)__r; }</c>
    /// or:     <c>static async (__inputs, __ctx) => { await CALL; return (object?)null; }</c>
    /// </summary>
    static ParenthesizedLambdaExpressionSyntax BuildInvokeLambda(ParsedStep step)
    {
        var callExpr = ParseExpression(step.InvokeCallText);
        var awaitExpr = AwaitExpression(callExpr);

        List<StatementSyntax> bodyStatements;
        if (step.HasResult)
        {
            // var __r = await CALL;
            var varDecl = LocalDeclarationStatement(
                VariableDeclaration(IdentifierName("var"))
                    .WithVariables(SingletonSeparatedList(
                        VariableDeclarator(Identifier("__r"))
                            .WithInitializer(EqualsValueClause(awaitExpr)))));
            // return (object?)__r;
            var returnStmt = ReturnStatement(
                CastExpression(
                    NullableType(PredefinedType(Token(SyntaxKind.ObjectKeyword))),
                    IdentifierName("__r")));
            bodyStatements = new List<StatementSyntax> { varDecl, returnStmt };
        }
        else
        {
            // await CALL;
            var awaitStmt = ExpressionStatement(awaitExpr);
            // return (object?)null;
            var returnStmt = ReturnStatement(
                CastExpression(
                    NullableType(PredefinedType(Token(SyntaxKind.ObjectKeyword))),
                    LiteralExpression(SyntaxKind.NullLiteralExpression)));
            bodyStatements = new List<StatementSyntax> { awaitStmt, returnStmt };
        }

        return ParenthesizedLambdaExpression()
            .WithModifiers(TokenList(Token(SyntaxKind.StaticKeyword), Token(SyntaxKind.AsyncKeyword)))
            .WithParameterList(ParameterList(SeparatedList(new[]
            {
                Parameter(Identifier("__inputs")),
                Parameter(Identifier("__ctx")),
            })))
            .WithBlock(Block(bodyStatements));
    }

    /// <summary>Builds <c>new int[] { i0, i1, … }</c> (empty initializer when the list is empty).</summary>
    static ArrayCreationExpressionSyntax IntArray(IEnumerable<int> ints)
        => ArrayCreationExpression(
            ArrayType(PredefinedType(Token(SyntaxKind.IntKeyword)))
                .WithRankSpecifiers(SingletonList(
                    ArrayRankSpecifier(SingletonSeparatedList<ExpressionSyntax>(
                        OmittedArraySizeExpression())))))
            .WithInitializer(InitializerExpression(
                SyntaxKind.ArrayInitializerExpression,
                SeparatedList<ExpressionSyntax>(ints.Select(i => (ExpressionSyntax)Num(i)))));

    /// <summary>
    /// Builds <c>global::System.TimeSpan.FromMilliseconds(ms)</c> or <c>null</c> when ms &lt;= 0.
    /// </summary>
    static ExpressionSyntax Timeout(int ms)
        => ms > 0
            ? InvocationExpression(
                MemberAccessExpression(
                    SyntaxKind.SimpleMemberAccessExpression,
                    ParseName("global::System.TimeSpan"),
                    IdentifierName("FromMilliseconds")))
                .WithArgumentList(ArgumentList(SingletonSeparatedList(Argument(Num(ms)))))
            : LiteralExpression(SyntaxKind.NullLiteralExpression);

    static AssignmentExpressionSyntax Set(string member, ExpressionSyntax value)
        => AssignmentExpression(SyntaxKind.SimpleAssignmentExpression, IdentifierName(member), value);

    static LiteralExpressionSyntax Num(int value)
        => LiteralExpression(SyntaxKind.NumericLiteralExpression, Literal(value));

    static LiteralExpressionSyntax Lit(string? value)
        => value is null
            ? LiteralExpression(SyntaxKind.NullLiteralExpression)
            : LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(value));
}
