//HintName: PUnitScenarios.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
#line hidden
using PUnit;
using System.Linq;
using System.Threading.Tasks;
using Demo;

namespace PUnit.Generated
{
    internal static class PUnitGenerated
    {
        public static global::System.Collections.Generic.IReadOnlyList<global::PUnit.Model.ScenarioDefinition> CreateAll() => new global::PUnit.Model.ScenarioDefinition[]
        {
            Scenario_Demo_ArrayScenarios_Import()
        };
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Initialize()
        {
            global::PUnit.ScenarioRegistry.Register("Demo.ArrayScenarios.Import", Scenario_Demo_ArrayScenarios_Import);
        }

        public static global::PUnit.Model.ScenarioDefinition Scenario_Demo_ArrayScenarios_Import()
        {
            var nodes = new global::PUnit.Model.ScenarioNode[4];
            nodes[0] = new global::PUnit.Model.ScenarioNode
            {
                Index = 0,
                StepId = "a90ff89cf522e934",
                Phase = "Given",
                OperationName = "UserExists",
                DisplayNameTemplate = "user alice exists",
                SourceFile = "",
                SourceLine = 78,
                GroupId = "g0",
                Timeout = null,
                DependsOn = new int[]
                {
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await Given.UserExists("alice");
#line hidden
                    return (object? )__r;
                }
            };
            nodes[1] = new global::PUnit.Model.ScenarioNode
            {
                Index = 1,
                StepId = "a90ff99cf522eae7",
                Phase = "Given",
                OperationName = "UserExists",
                DisplayNameTemplate = "user bob exists",
                SourceFile = "",
                SourceLine = 79,
                GroupId = "g0",
                Timeout = null,
                DependsOn = new int[]
                {
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await Given.UserExists("bob");
#line hidden
                    return (object? )__r;
                }
            };
            nodes[2] = new global::PUnit.Model.ScenarioNode
            {
                Index = 2,
                StepId = "e0803707472d5274",
                Phase = "When",
                OperationName = "ImportUsers",
                DisplayNameTemplate = "importing users",
                SourceFile = "",
                SourceLine = 82,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0,
                    1
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await When.ImportUsers(new global::Demo.User[] { __inputs.Get<global::Demo.User>(0), __inputs.Get<global::Demo.User>(1) });
#line hidden
                    return (object? )__r;
                }
            };
            nodes[3] = new global::PUnit.Model.ScenarioNode
            {
                Index = 3,
                StepId = "cdc74a6d6973fd48",
                Phase = "Then",
                OperationName = "ImportShouldContainUsers",
                DisplayNameTemplate = "the import should contain the users",
                SourceFile = "",
                SourceLine = 83,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0,
                    1,
                    2
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    await Then.ImportShouldContainUsers(__inputs.Get<global::Demo.Import>(2), new global::Demo.User[] { __inputs.Get<global::Demo.User>(0), __inputs.Get<global::Demo.User>(1) });
#line hidden
                    return (object? )null;
                }
            };
            return new global::PUnit.Model.ScenarioDefinition
            {
                ScenarioId = "903e3e1cb803db83",
                DisplayName = "array import",
                MethodName = "Demo.ArrayScenarios.Import",
                SourceFile = "",
                SourceLine = 74,
                Timeout = null,
                Nodes = nodes
            };
        }
    }
}
