namespace Freista.Generator.Emit;

/// <summary>
/// Emits the Microsoft.Testing.Platform entry point: a <c>Main</c> that forwards its command-line
/// arguments to <c>Freista.Mtp.FreistaTestApplication.RunAsync</c> (which registers Freista's
/// <c>ITestFramework</c> and runs the host) and returns its exit code.
/// </summary>
/// <remarks>
/// Mirrors xUnit's auto-generated entry point: "just add the package" UX. Emission is gated by the
/// generator on the MSBuild property <c>FreistaGenerateProgram</c> (default <c>true</c>); when a
/// consumer sets it to <c>false</c> they supply their own <c>Program.cs</c> and call the same public
/// bootstrap directly. The generated type is <c>internal</c> and fully qualifies the bootstrap so it
/// needs no usings and cannot collide with consumer code.
/// </remarks>
internal static class EntryPointEmitter
{
    public const string HintName = "FreistaProgram.g.cs";

    public static string Emit() =>
        """
        // <auto-generated/>
        #nullable enable
        #pragma warning disable CS1591
        #line hidden

        namespace Freista.Generated
        {
            /// <summary>Auto-generated Microsoft.Testing.Platform entry point for this Freista test project.</summary>
            [global::System.CodeDom.Compiler.GeneratedCode("Freista.Generator", null)]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
            internal static class FreistaProgram
            {
                public static global::System.Threading.Tasks.Task<int> Main(string[] args)
                    => global::Freista.Mtp.FreistaTestApplication.RunAsync(args);
            }
        }

        """;
}
