using System.Linq;
using Xunit;

namespace PUnit.Generator.Test;

/// <summary>
/// The generator emits the MTP entry point (<c>Program.cs</c> ⇒ a <c>Main</c> calling
/// <c>PUnit.Mtp.PUnitTestApplication.RunAsync(args)</c>) so a consumer gets "just add the package"
/// UX. Emission is gated on the MSBuild property <c>PUnitGenerateProgram</c> (default <c>true</c>);
/// setting it to <c>false</c> suppresses the entry point so the user can supply their own
/// <c>Program.cs</c> and call the same public bootstrap directly.
/// </summary>
public class EntryPointGenerationTests
{
    private const string EntryPointHint = "PUnitProgram.g.cs";

    private static string Source => SampleSources.Dsl + SampleSources.LinearScenario;

    [Fact]
    public void Entry_point_is_emitted_by_default()
    {
        var files = GeneratorHarness.RunGeneratedFiles(Source, generateProgram: null);

        Assert.True(files.ContainsKey(EntryPointHint), "expected the entry point to be generated by default");
        var program = files[EntryPointHint];
        Assert.Contains("PUnit.Mtp.PUnitTestApplication.RunAsync", program, StringComparison.Ordinal);
        Assert.Contains("static", program, StringComparison.Ordinal);
        Assert.Contains("Main", program, StringComparison.Ordinal);
    }

    [Fact]
    public void Entry_point_is_emitted_when_property_is_true()
    {
        var files = GeneratorHarness.RunGeneratedFiles(Source, generateProgram: "true");

        Assert.True(files.ContainsKey(EntryPointHint), "expected the entry point when PUnitGenerateProgram=true");
    }

    [Fact]
    public void Entry_point_is_suppressed_when_property_is_false()
    {
        var files = GeneratorHarness.RunGeneratedFiles(Source, generateProgram: "false");

        Assert.False(files.ContainsKey(EntryPointHint), "PUnitGenerateProgram=false must suppress the entry point");
        // The scenario manifest is still generated; only the entry point is gated.
        Assert.True(files.ContainsKey("PUnitScenarios.g.cs"));
    }

    [Fact]
    public void Property_value_is_case_insensitive_for_false()
    {
        var files = GeneratorHarness.RunGeneratedFiles(Source, generateProgram: "False");

        Assert.False(files.ContainsKey(EntryPointHint), "the gate must treat 'False' like 'false'");
    }

    [Fact]
    public void Entry_point_is_emitted_even_without_any_scenarios()
    {
        // No [Scenario] methods: the manifest is skipped, but a test app still needs an entry point.
        var files = GeneratorHarness.RunGeneratedFiles(SampleSources.Dsl, generateProgram: null);

        Assert.True(files.ContainsKey(EntryPointHint));
        Assert.False(files.ContainsKey("PUnitScenarios.g.cs"));
    }

    [Fact]
    public void Generated_entry_point_passes_args_through()
    {
        var program = GeneratorHarness.RunGeneratedFiles(Source)[EntryPointHint];

        // The Main forwards its string[] args to the bootstrap and returns its int exit code.
        Assert.Contains("string[] args", program, StringComparison.Ordinal);
        Assert.Contains("args", program, StringComparison.Ordinal);
    }

    [Fact]
    public void Generated_entry_point_compiles_against_the_real_bootstrap()
    {
        var program = GeneratorHarness.RunGeneratedFiles(Source)[EntryPointHint];

        // Compiling against PUnit.Mtp proves the emitted Main binds to the real RunAsync signature
        // (catches drift between the generator and PUnitTestApplication).
        var errors = GeneratorHarness.CompileWithMtp(program);

        Assert.True(errors.IsEmpty, "generated entry point did not compile: " + string.Join("; ", errors));
    }
}
