//HintName: FreistaScenarios.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
#line hidden
using Freista;
using System.Linq;
using System.Threading.Tasks;
using CondDemo;

namespace Freista.Generated
{
    internal static class FreistaGenerated
    {
        public static global::System.Collections.Generic.IReadOnlyList<global::Freista.Model.ScenarioDefinition> CreateAll() => new global::Freista.Model.ScenarioDefinition[]
        {
            Scenario_CondDemo_IfElseScenarios_Routing()
        };
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Initialize()
        {
            global::Freista.ScenarioRegistry.Register("CondDemo.IfElseScenarios.Routing", Scenario_CondDemo_IfElseScenarios_Routing);
        }

        public static global::Freista.Model.ScenarioDefinition Scenario_CondDemo_IfElseScenarios_Routing()
        {
            var nodes = new global::Freista.Model.ScenarioNode[6];
            nodes[0] = new global::Freista.Model.ScenarioNode
            {
                Index = 0,
                StepId = "82131adf5aaa5744",
                Phase = "Given",
                OperationName = "PatientExists",
                DisplayNameTemplate = "patient Jane exists",
                SourceFile = "",
                SourceLine = 74,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await Given.PatientExists("Jane");
#line hidden
                    return (object? )__r;
                }
            };
            nodes[1] = new global::Freista.Model.ScenarioNode
            {
                Index = 1,
                StepId = "708ab3852bf5e730",
                Phase = "Given",
                OperationName = "IsPriority",
                DisplayNameTemplate = "the patient is priority",
                SourceFile = "",
                SourceLine = 77,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0
                },
                EvaluateCondition = static __o => ((bool)__o!) ? true : false,
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await Given.IsPriority();
#line hidden
                    return (object? )__r;
                }
            };
            nodes[2] = new global::Freista.Model.ScenarioNode
            {
                Index = 2,
                StepId = "80a795d75cc5f534",
                Phase = "When",
                OperationName = "CreateUrgent",
                DisplayNameTemplate = "creating an urgent appointment",
                SourceFile = "",
                SourceLine = 78,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0,
                    1
                },
                Guards = new global::Freista.Model.Guard[]
                {
                    new global::Freista.Model.Guard(1, true)
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await When.CreateUrgent(__inputs.Get<global::CondDemo.Patient>(0));
#line hidden
                    return (object? )__r;
                }
            };
            nodes[3] = new global::Freista.Model.ScenarioNode
            {
                Index = 3,
                StepId = "f0fbe5209a25ea0f",
                Phase = "When",
                OperationName = "CreateStandard",
                DisplayNameTemplate = "creating a standard appointment",
                SourceFile = "",
                SourceLine = 80,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0,
                    1
                },
                Guards = new global::Freista.Model.Guard[]
                {
                    new global::Freista.Model.Guard(1, false)
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await When.CreateStandard(__inputs.Get<global::CondDemo.Patient>(0));
#line hidden
                    return (object? )__r;
                }
            };
            nodes[4] = new global::Freista.Model.ScenarioNode
            {
                Index = 4,
                StepId = "7f4b5d73d9c42f6a",
                Phase = "When",
                OperationName = "Merge",
                DisplayNameTemplate = "«merge appointment»",
                SourceFile = null,
                SourceLine = 0,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                },
                MergeSources = new int[]
                {
                    2,
                    3
                },
                IsSynthetic = true,
                Invoke = static (__inputs, __ctx) => global::System.Threading.Tasks.Task.FromResult<object?>(null)
            };
            nodes[5] = new global::Freista.Model.ScenarioNode
            {
                Index = 5,
                StepId = "be44904d735b2dcf",
                Phase = "Then",
                OperationName = "AppointmentExists",
                DisplayNameTemplate = "the appointment should exist",
                SourceFile = "",
                SourceLine = 82,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    4
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    await Then.AppointmentExists(__inputs.Get<global::CondDemo.Appointment>(4));
#line hidden
                    return (object? )null;
                }
            };
            return new global::Freista.Model.ScenarioDefinition
            {
                ScenarioId = "28414318685d340d",
                DisplayName = "priority routing",
                MethodName = "CondDemo.IfElseScenarios.Routing",
                ClassDisplayName = null,
                SourceFile = "",
                SourceLine = 72,
                Timeout = null,
                Nodes = nodes
            };
        }
    }
}
