//HintName: FreistaScenarios.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
#line hidden
using Freista;
using System.Linq;
using System.Threading.Tasks;
using Demo;

namespace Freista.Generated
{
    internal static class FreistaGenerated
    {
        public static global::System.Collections.Generic.IReadOnlyList<global::Freista.Model.ScenarioDefinition> CreateAll() => new global::Freista.Model.ScenarioDefinition[]
        {
            Scenario_Demo_TupleScenarios_Booking()
        };
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Initialize()
        {
            global::Freista.ScenarioRegistry.Register("Demo.TupleScenarios.Booking", Scenario_Demo_TupleScenarios_Booking);
        }

        public static global::Freista.Model.ScenarioDefinition Scenario_Demo_TupleScenarios_Booking()
        {
            var nodes = new global::Freista.Model.ScenarioNode[5];
            nodes[0] = new global::Freista.Model.ScenarioNode
            {
                Index = 0,
                StepId = "d1259ee6dfe4be67",
                Phase = "Given",
                OperationName = "DatabaseIsClean",
                DisplayNameTemplate = "database is clean",
                SourceFile = "",
                SourceLine = 76,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    await Given.DatabaseIsClean();
#line hidden
                    return (object? )null;
                }
            };
            nodes[1] = new global::Freista.Model.ScenarioNode
            {
                Index = 1,
                StepId = "0f2a20f6512c233b",
                Phase = "Given",
                OperationName = "PatientExists",
                DisplayNameTemplate = "patient Jane exists",
                SourceFile = "",
                SourceLine = 79,
                GroupId = "g1",
                Timeout = null,
                DependsOn = new int[]
                {
                    0
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await Given.PatientExists("Jane");
#line hidden
                    return (object? )__r;
                }
            };
            nodes[2] = new global::Freista.Model.ScenarioNode
            {
                Index = 2,
                StepId = "82e8180f0d8533cc",
                Phase = "Given",
                OperationName = "AvailableSlot",
                DisplayNameTemplate = "an available slot exists",
                SourceFile = "",
                SourceLine = 80,
                GroupId = "g1",
                Timeout = null,
                DependsOn = new int[]
                {
                    0
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await Given.AvailableSlot();
#line hidden
                    return (object? )__r;
                }
            };
            nodes[3] = new global::Freista.Model.ScenarioNode
            {
                Index = 3,
                StepId = "6662873acd4eb4ed",
                Phase = "When",
                OperationName = "CreateAppointment",
                DisplayNameTemplate = "creating an appointment",
                SourceFile = "",
                SourceLine = 82,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    1,
                    2
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await When.CreateAppointment(__inputs.Get<global::Demo.Patient>(1), __inputs.Get<global::Demo.Slot>(2));
#line hidden
                    return (object? )__r;
                }
            };
            nodes[4] = new global::Freista.Model.ScenarioNode
            {
                Index = 4,
                StepId = "14f28602f0f9d930",
                Phase = "Then",
                OperationName = "AppointmentExists",
                DisplayNameTemplate = "the appointment should exist",
                SourceFile = "",
                SourceLine = 83,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    3
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    await Then.AppointmentExists(__inputs.Get<global::Demo.Appointment>(3));
#line hidden
                    return (object? )null;
                }
            };
            return new global::Freista.Model.ScenarioDefinition
            {
                ScenarioId = "c437082da1b43ab4",
                DisplayName = "tuple booking",
                MethodName = "Demo.TupleScenarios.Booking",
                ClassDisplayName = null,
                SourceFile = "",
                SourceLine = 74,
                Timeout = null,
                Nodes = nodes
            };
        }
    }
}
