//HintName: FreistaScenarios.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS1591
#line hidden
using Freista;
using System.Linq;
using System.Threading.Tasks;
using ResourceDemo;

namespace Freista.Generated
{
    internal static class FreistaGenerated
    {
        public static global::System.Collections.Generic.IReadOnlyList<global::Freista.Model.ScenarioDefinition> CreateAll() => new global::Freista.Model.ScenarioDefinition[]
        {
            Scenario_ResourceDemo_ResourceScenarios_SuspendedUserCannotSignIn()
        };
        [global::System.Runtime.CompilerServices.ModuleInitializer]
        internal static void Initialize()
        {
            global::Freista.ScenarioRegistry.Register("ResourceDemo.ResourceScenarios.SuspendedUserCannotSignIn", Scenario_ResourceDemo_ResourceScenarios_SuspendedUserCannotSignIn);
        }

        public static global::Freista.Model.ScenarioDefinition Scenario_ResourceDemo_ResourceScenarios_SuspendedUserCannotSignIn()
        {
            var nodes = new global::Freista.Model.ScenarioNode[3];
            nodes[0] = new global::Freista.Model.ScenarioNode
            {
                Index = 0,
                StepId = "b60cc37490078dc8",
                Phase = "Given",
                OperationName = "UserExists",
                DisplayNameTemplate = "user jane@acme.com exists",
                SourceFile = "",
                SourceLine = 80,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await Given.UserExists("jane@acme.com");
#line hidden
                    await __ctx.Resources.Create(__r);
#line hidden
                    return (object? )__r;
                }
            };
            nodes[1] = new global::Freista.Model.ScenarioNode
            {
                Index = 1,
                StepId = "54489df35cd31516",
                Phase = "When",
                OperationName = "Suspend",
                DisplayNameTemplate = "suspending the user",
                SourceFile = "",
                SourceLine = 81,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    0
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    var __r = await When.Suspend(__inputs.Get<global::ResourceDemo.User>(0));
#line hidden
                    await __ctx.Resources.Edit(__inputs.Get<global::ResourceDemo.User>(0));
#line hidden
                    await __ctx.Resources.Edit(__r);
#line hidden
                    return (object? )__r;
                }
            };
            nodes[2] = new global::Freista.Model.ScenarioNode
            {
                Index = 2,
                StepId = "9805285c8a9f5d48",
                Phase = "Then",
                OperationName = "CannotSignIn",
                DisplayNameTemplate = "the user cannot sign in",
                SourceFile = "",
                SourceLine = 82,
                GroupId = null,
                Timeout = null,
                DependsOn = new int[]
                {
                    1
                },
                Invoke = static async (__inputs, __ctx) =>
                {
                    await Then.CannotSignIn(__inputs.Get<global::ResourceDemo.User>(1));
#line hidden
                    await __ctx.Resources.Read(__inputs.Get<global::ResourceDemo.User>(1));
#line hidden
                    return (object? )null;
                }
            };
            return new global::Freista.Model.ScenarioDefinition
            {
                ScenarioId = "c01f329e4fc6cd1a",
                DisplayName = "suspended user cannot sign in",
                MethodName = "ResourceDemo.ResourceScenarios.SuspendedUserCannotSignIn",
                ClassDisplayName = null,
                SourceFile = "",
                SourceLine = 78,
                Timeout = null,
                Nodes = nodes
            };
        }
    }
}
